-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 16:51:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` VARCHAR(40) NOT NULL,
  `name` MEDIUMTEXT NULL,
  `date` DATE NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nearby_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nearby_locations` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `event_id1` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`, `event_id1`),
  INDEX `fk_nearby_locations_event_idx` (`event_id1` ASC) VISIBLE,
  CONSTRAINT `fk_nearby_locations_event`
    FOREIGN KEY (`event_id1`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_user` (
  `id` VARCHAR(45) NOT NULL,
  `event_id1` VARCHAR(40) NOT NULL,
  `user_id1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `event_id1`, `user_id1`),
  INDEX `fk_event_user_event1_idx` (`event_id1` ASC) VISIBLE,
  INDEX `fk_event_user_user1_idx` (`user_id1` ASC) VISIBLE,
  CONSTRAINT `fk_event_user_event1`
    FOREIGN KEY (`event_id1`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_user_user1`
    FOREIGN KEY (`user_id1`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
